language: node_js

jobs:
  include:
  - python: '2.7'
    env: TEST_PATTERN='*_tests.py' COVERAGE_THRESHHOLD=95
  - python: '3.7'
    env: TEST_PATTERN='*_2_3_tests.py' COVERAGE_THRESHHOLD=23

node_js:
- '11.8.0'

install:
- ./install_dependencies.sh

script:
- coverage run --source="./matchmaker","./seqr","./reference_data" --omit="*/migrations/*","*/apps.py" manage.py test -p $TEST_PATTERN -v 2 reference_data seqr matchmaker
- coverage report --fail-under=$COVERAGE_THRESHHOLD
- cd ui/
- npm test

addons:
  postgresql: '9.6'

notifications:
  slack:
    secure: tYNwi4kff+8FWbv+nWqKZt28Qez0Dv77rJG6nvdiaO7QgPZmaiG5l8NqYdxV63CMgNzHwTFAz8ca9uOoh06o7+HuiFNNiqXEAu8umLvlnvkKT6itSDyImxxD7ypitUwcBEKkNy1fxhrLRPQVLjxz37885kA/VtWpm19A5vQ8A7w=

