#####################################################
####### SETTINGS THAT MAY NEED TO BE MODIFIED #######

POSTGRES_DISK_SIZE: '200Gb'   # used when creating the GKE cluster on gcloud deployments
SEQR_STATIC_FILES_DISK_SIZE: '50Gb'  # used when creating the GKE cluster on gcloud deployments
ELASTICSEARCH_DISK_SIZE: 200  # used when creating the GKE cluster on gcloud deployments

NUM_NODES_PER_NODE_POOL: 4    # used when creating nodes for gcloud deployments

GUNICORN_WORKER_THREADS: 4    # number of webserver threads

###########################################################
####### SETTINGS THAT SHOULDN'T NEED TO BE MODIFIED #######

DOCKER_IMAGE_PREFIX: 'gcr.io/seqr-project'
IMAGE_PULL_POLICY: 'Always'

DEPLOYMENT_TEMP_DIR: '/tmp'
DATA_DIR: '/data'
STATIC_MEDIA_DIR: '/seqr_static_files'
MME_CONFIG_DIR: '/mme'

POSTGRES_SERVICE_HOSTNAME: postgres
POSTGRES_USERNAME: postgres
ELASTICSEARCH_SERVICE_HOSTNAME: elasticsearch
KIBANA_SERVICE_HOSTNAME: kibana
REDIS_SERVICE_HOSTNAME: redis

COCKPIT_SERVICE_PORT: 9090
POSTGRES_SERVICE_PORT: 5432
ELASTICSEARCH_SERVICE_PORT: 9200
KIBANA_SERVICE_PORT: 5601
SEQR_SERVICE_PORT: 8000
REDIS_SERVICE_PORT: 6379
PIPELINE_RUNNER_SERVICE_PORT: 30005

SEQR_UI_DEV_PORT: 3000


